### ISSUE TITLE
Failures during yarn migrate

### ISSUE THREAD

**Issue by rbharath** [dharmaprotocol/dharma-react-starter-kit#2]
I'm attempting to get the starter kit running following the directions on the readme. I'm on Ubuntu 16.04 and running `yarn` version 1.3.2. Everything works until the migration:

```
rbharath@rbharath-XPS-13-9360:~/dharma-react-starter-kit$ yarn migrate
yarn run v1.3.2
warning package.json: "dependencies" has dependency "dotenv" with range "^2.0.0" that collides with a dependency in "devDependencies" of the same name with version "2.0.0"
$ truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x32dfbe7bb958c05faae590ef2af5b3ce177b6c8eaa4c94832c296d05c8c11421
  Migrations: 0x4fb662cd31fc46f5886c1b377ef05271d0c2d8ed
Saving artifacts...
Running migration: 2_deploy_dharma_contracts.js
/home/rbharath/dharma-react-starter-kit/migrations/2_deploy_dharma_contracts.js:14
    return deployer.deploy(DebtRegistry).then(async () => {
                                                    ^

SyntaxError: Unexpected token (
    at Object.createScript (vm.js:56:10)
    at /home/rbharath/dharma-react-starter-kit/node_modules/truffle/build/cli.bundled.js:203485:23
    at tryToString (fs.js:457:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It looks like an error with Babel not running perhaps? Any pointers to figure this out would be much appreciated :)

**Comment by rbharath** [comment]
Figured it out. For reference, I was on node 6.13 since Ubuntu 16.04 doesn't install a more recent node by default. Upgrading to a more recent version of node fixed the issue.

**Comment by nadavhollander** [comment]
@rbharath Thanks for digging into this.  Updating the README right now.
